---
title: Open Savannah
timezone: UTC
markdown: kramdown
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: yall@opensavannah.org  
description: 'Part of the Code for America Brigade network, we are a volunteer group
  of developers, designers, data geeks, and citizen activists who use creative technology
  to solve civic and social problems.'
baseurl: ''
url: http://opensavannah.org
hackpad_url: https://opensavannah.hackpad.com/
twitter_url: https://twitter.com/opensavannah
github_url: https://github.com/opensavannah
meetup_url: https://meetup.com/opensavannah
blog_url: https://medium.com/opensavannah
events_url: http://cal.codeforboston.org
slack_url: https://techsav.co/wp-login.php?action=slack-invitation