# Site settings
title: Code for Brasília
email: codeforbrasilia@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Fazemos parte da rede Code for Brasil e somos um grupo de hackers cívicos (desenvolvedores, designers, empreendedores, sociedade civil engajada, etc) que utiliza da tecnologia para resolver problemas da sociedade.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://codeforbrasilia.org" # the base hostname & protocol for your site
twitter_username: codeforbrasilia
github_username:  codeforbrasilia
meetup_path:      Code-For-Brasilia

# Build settings
markdown: kramdown
